### ISSUE TITLE
How to remove the environment logging in the console?

### ISSUE THREAD

**Issue by HeegerGao** [Rafael1s/Deep-Reinforcement-Learning-Udacity#2]
I have a lot of this kind of logging when a new episode begins:  Track generation: 1220..1529 -> 309-tiles track

I noticed that there is no such kind of logging in your console in the .ipynb page. Can you tell me how to remove them? Thank you very much.

**Comment by Rafael1s** [comment]
Each environment operates in its own way.
Please tell me in which project is this type of message going?

**Comment by HeegerGao** [comment]
I am sorry for my ambiguous expression.  I am referring to Car_racing-v0 environment, to be specific, this link: https://github.com/Rafael1s/Deep-Reinforcement-Learning-Udacity/blob/master/CarRacing-From-Pixels-PPO/CarRacing_PPO-2760epis_902score.ipynb

As I said, there is no boresome logging infos in your output but they do exist in my Python console when I am using Car_racing-v0 environment. I want to ask for your useful method.

By the way, I did't notice that this project is such a big project so that I ask former question with no details mentioned, because I was searching some code for Car_racing-v0 and found that .ipynb page and then committed an issue.

**Comment by Rafael1s** [comment]
I think I know what the problem is with the big track.
Set verbose = 0, i.e.
env = gym.make ('CarRacing-v0', verbose = 0)

**Comment by HeegerGao** [comment]
It works. Thank you very much!
